export {default as Home} from './Home/Home'
export {default as Signin} from './Signin/Signin'
export {default as Signup} from './Signup/Signup'
export {default as StudentProfile} from './StudentProfile/StudentProfile'
export {default as AdminProfile} from './AdminProfile/AdminProfile'
export {default as CourseDetails} from './CourseDetails/CourseDetails'